# Generated by Django 4.2.21 on 2025-06-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'STARTED'), (2, 'COMPLETED'), (3, 'OPTED_OUT')], default=0),
        ),
    ]
