# Generated by Django 4.2.21 on 2025-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ended_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateField(),
        ),
    ]
